version: '3'

services:
###> doctrine/doctrine-bundle ###
  sf-php:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: 'sf-php'
    hostname: 'sf-php'
    ports:
      - '8180:80'
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      - sf-db
    networks:
      - sf-net
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  sf-mailer:
    image: axllent/mailpit
    container_name: 'sf-mailer'
    hostname: 'sf-mailer'
    ports:
      - '1025'
      - '8125:8025'
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

